### ISSUE TITLE
computer-programming lab_numerical approximation_quiz

### ISSUE THREAD

**Issue by gayatripurigilla** [virtual-labs/computer-programming-responsive-iiith#101]
**Defect description**when we attempt for a quiz in numerical approximation and click on submit option the correct answers are given in a new window.in this the 4th answer is given as a empty text field.**steps to reproduce the issue:***  click on **iiit hyderabad** under the participating institutes in vlabs main website.*  click on link of **computer-programming lab**.*  click on **numerical approximation**.*  click on quiz and after attempting press the submit button**expected result:**a webpage with all correct answers to be displayed**actual result:**the last answer is not given.**Screenshots:**![84](https://gitlab.com/aakarsh/virtual-labs-internship-aakarsh/uploads/e13322658d84ee18cf5c0dc1d636b576/84.JPG)

**Comment by kurasaiteja** [comment]
Same issue #146
