### ISSUE TITLE
computer-programming lab_recursion_further readings

### ISSUE THREAD

**Issue by gayatripurigilla** [virtual-labs/computer-programming-responsive-iiith#103]
**Defect description:**when click on hyperlinks   1. http://www.tech-faq.com/recursion.html   1. http://en.wikipedia.org/wiki/recursion_(computer-science) below further reading option in recursion experiment we are redirected to a page which talks about pointers**steps to reproduce the issue:***  click on **iiit hyderabad** under the participating institutes in the vlabs main website.*  click on **computer-programming lab***  click on **recursion***  click on hyperlinks below the **further readings** option.**expected result:**page about recursion is expected.**actual result:**page about pointers is dispayed.**Screenshots:**![53](https://gitlab.com/aakarsh/virtual-labs-internship-aakarsh/uploads/f6048b20220eba820ecc4c3ccd22020a/53.JPG)![54](https://gitlab.com/aakarsh/virtual-labs-internship-aakarsh/uploads/3a5744f4770a6149e8e3b634847bff4c/54.JPG)![55](https://gitlab.com/aakarsh/virtual-labs-internship-aakarsh/uploads/13ee2c390679709142642c5882a99d11/55.JPG)

**Comment by kurasaiteja** [comment]
Same issue #151
