### ISSUE TITLE
computer-programming_lab-numerical_approximation-quiz

### ISSUE THREAD

**Issue by gayatripurigilla** [virtual-labs/computer-programming-responsive-iiith#123]
**description**the answer for the last question is not being displayed**steps to reach the issue**1)select computer-programming lab2)select number approximations and click on quiz3)answer the questions and check the score and correct answers**expected result**list of all correct answers**actual result**only first four answers are being displayed**Screenshot**![Screenshot__444_](https://gitlab.com/thefirefist/virtual-labs-internship-pranay/uploads/ed68b04a76146b704974a43e453452e7/Screenshot__444_.png)

**Comment by kurasaiteja** [comment]
Same issue: #101
