### ISSUE TITLE
computer-programming_lab-recursion

### ISSUE THREAD

**Issue by gayatripurigilla** [virtual-labs/computer-programming-responsive-iiith#124]
**description**in the further reading section , the wikipedia link points to a pointer page**steps to reach the issue**1)select computer-programming lab2)select recursion3)select the wikipedia link in further reading page**expected result**a wikipedia page on recursion**actual result**a wikipedia page on pointers**Screenshot**![Screenshot__449_](https://gitlab.com/thefirefist/virtual-labs-internship-pranay/uploads/d493097a18bdfdb9fafbbcd2777efd7f/Screenshot__449_.png)

**Comment by kurasaiteja** [comment]
same issue #151
