### ISSUE TITLE
computer-programming-lab_functions_graph-quiz

### ISSUE THREAD

**Issue by gayatripurigilla** [virtual-labs/computer-programming-responsive-iiith#140]
the 7th and 8th questions are not displayed.steps to reproduce the issue:1. open computer-programming lab.2. click on functions.3.select quiz.expected result: given 6 questions are to be evaluated..actual result: 8 questions are evaluated..Screenshot:![untitled](https://gitlab.com/varsh/virtual-labs-internship-varsha/uploads/d16a8a1043bdf4cda56b97642ff7b02b/untitled.png)![1](https://gitlab.com/varsh/virtual-labs-internship-varsha/uploads/b6fb7cf912ddef9ed6146a1862d76b4e/1.png)

**Comment by kurasaiteja** [comment]
Same issue #98
