### ISSUE TITLE
computer-programming-lab_functions_quiz

### ISSUE THREAD

**Issue by gayatripurigilla** [virtual-labs/computer-programming-responsive-iiith#141]
Defect description: more answers than questions. expected content : there should be 8 questions but we have only 6 questions. when we click on results we are getting answers for 8 questions.![Screenshot__47_](https://gitlab.com/prem_/virtual-labs-internship-prem/uploads/1986f1ac474042ebf9cfbdf95418b3e4/Screenshot__47_.png)![Screenshot__48_](https://gitlab.com/prem_/virtual-labs-internship-prem/uploads/aeba446a56ee9abb3946a896b63969f3/Screenshot__48_.png)

**Comment by kurasaiteja** [comment]
Same issue is #98
