### ISSUE TITLE
Need to update content on "About this lab" page 

### ISSUE THREAD

**Issue by khushpreet-kaur** [Virtual-Labs/computer-programming-responsive-iiith#3]
Explore this lab, Prerequisites and References sections in "About this lab page" needs to be updated with updated content. It should be more elaborate.

**Comment by madhavipuliraju** [comment]
@khushpreet-kaur please fix this as soon as possible because this lab is selected for the demo

**Comment by khushpreet-kaur** [comment]
@madhavipuliraju  This issue is fixed now.
