### ISSUE TITLE
Feedback link is redirecting to 404 page

### ISSUE THREAD

**Issue by khushpreet-kaur** [Virtual-Labs/computer-programming-responsive-iiith#4]
Need to fix link for the feedback link in "About this lab"  page.

**Comment by madhavipuliraju** [comment]
@khushpreet-kaur please fix this as soon as posible because this lab is selected for the demo

**Comment by khushpreet-kaur** [comment]
@madhavipuliraju Yes Madhavi.  It's fixed now.
