### ISSUE TITLE
QA_Computer Programming_Landing page_Like Button

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/computer-programming-responsive-iiith#56]
Defect Description:
In the Landing page of "Computer Programming Lab", the like button is redirecting to the page which is not found. Where as the page should redirect to the appropriate Vlabs face book page.

Actual Result :
In the Landing page of "Computer Programming Lab", the like button is redirecting to the page which is not found.

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_cpl_i1](https://cloud.githubusercontent.com/assets/13479177/19961551/11d97842-a1d5-11e6-81f1-be9bdee20574.png)

**Comment by sravanthimodepu** [comment]
Issue is not yet fixed.
