### ISSUE TITLE
QA_Landing page_View About page in studio button

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/computer-programming-responsive-iiith#57]
Defect Description:
In the Landing page of "Computer Programming Lab", when we click on the View About Page in Studio button a new page is opening with an error message saying Unable to Connect. Where as on click the page should navigate to the appropriate page.

Actual Result :
In the Landing page of "Computer Programming Lab", when we click on the View About Page in Studio button a new page is opening with an error message saying Unable to Connect.

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_cpl_i2](https://cloud.githubusercontent.com/assets/13479177/19961732/f2095590-a1d5-11e6-88a4-a944d7d4c466.png)

**Comment by sravanthimodepu** [comment]
As the **View About Page In Studio** button was removed from the landing page of the Natural Language Processing Lab, differing this issue.
