### ISSUE TITLE
QA_Computer Programming_ Home Page_Unwanted Text

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/computer-programming-responsive-iiith#58]
Defect Description:
In the Home page of "Computer Programming Lab", when we select the entire page, unwanted test is present. Where as the unwanted text should not be present near the Heading.

Actual Result
In the Landing page of "Computer Programming Lab", when we click on the View About Page in Studio button a new page is opening with an error message saying Unable to Connect.

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_cpl_i3](https://cloud.githubusercontent.com/assets/13479177/19961795/54e3e180-a1d6-11e6-9c31-a1e155f5402b.png)

**Comment by sravanthimodepu** [comment]
Unwanted text was visible now and the issue is fixed.
