### ISSUE TITLE
QA_Computer Programming_All pages - "View unit in studio" button

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/computer-programming-responsive-iiith#59]
Defect Description:
In all the pages of "Computer Programming", when we click on the "View unit in studio" button navigating to a new page with an error message saying Unable to Connect. Where as on click the page should navigate to the appropriate page.

Actual Result :
In all the pages of "Computer Programming Lab", when we click on the "View unit in studio" button navigating to a new page with an error message saying Unable to Connect.

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_cpl_i4](https://cloud.githubusercontent.com/assets/13479177/19961847/ab25f31c-a1d6-11e6-8618-d0b2c545aa74.png)

**Comment by sravanthimodepu** [comment]
Issue is not yet fixed.
