### ISSUE TITLE
QA_Computer Programming_All pages - Footer and Social media icons

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/computer-programming-responsive-iiith#60]
Defect Description:
In all the pages of "Computer Programming Lab", the footer is not responsive. When we zoom / out the icons are moving and the links are over lapping on other links. Where as the footer should be responsive and the social media images should be stable.

Actual Result :
In all the pages of "Computer Programming Lab", the footer is not responsive. When we zoom / out the icons are moving and the links are over lapping on other links.

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_cpl_i5](https://cloud.githubusercontent.com/assets/13479177/19961896/ee6790d6-a1d6-11e6-8a7c-6e413e2072ff.png)

**Comment by sravanthimodepu** [comment]
Issue is not yet fixed.
