### ISSUE TITLE
QA_Strings_Experiment_Improper alignment 

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/computer-programming-responsive-iiith#65]
Defect Description:
In the experiment page of "Strings" of this lab, alignment of the simulation is improper. The simulation is exceeding the page. Where as the simulation should get adjusted in the page itself.

Actual Result :
In the experiment page of "Strings" of this lab, alignment of the simulation is improper. The simulation is exceeding the page.

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_cpl_i9](https://cloud.githubusercontent.com/assets/13479177/19962546/03745f7e-a1da-11e6-8f45-51456802b617.png)

**Comment by sravanthimodepu** [comment]
Adjusted the length and width of the simulation. Hence issue is fixed now.
