### ISSUE TITLE
QA_Functions_Experiment_Improper alignment 

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/computer-programming-responsive-iiith#66]
Defect Description:
In the experiment page of "Functions" of this lab, alignment of the simulation is improper. The simulation is exceeding the page. Where as the simulation should get adjusted in the page itself.

Actual Result :
In the experiment page of "Functions" of this lab, alignment of the simulation is improper. The simulation is exceeding the page.

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_cpl_i10](https://cloud.githubusercontent.com/assets/13479177/19962589/3defc0ee-a1da-11e6-8f1a-1f07f332a69a.png)

**Comment by sravanthimodepu** [comment]
Aligned the length and width of the simulation properly to view the simulation in a better way. Hence the issue is fixed.
