### ISSUE TITLE
QA_Numerical Approximation_Experiment_Improper alignment

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/computer-programming-responsive-iiith#67]
Defect Description:
In the experiment page of "Numerical Approximation" of this lab, alignment of the simulation is improper. The simulation is exceeding the page. Where as the simulation should get adjusted in the page itself.

Actual Result :
In the experiment page of "Numerical Approximation" of this lab, alignment of the simulation is improper. The simulation is exceeding the page.

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_cpl_i11](https://cloud.githubusercontent.com/assets/13479177/19962632/7093446c-a1da-11e6-8fe8-33b5c95c92df.png)

**Comment by sravanthimodepu** [comment]
While trying to adjust the simulation's length and width to view it completely, the graph in the simulation is overlapping with the other components.
