### ISSUE TITLE
QA_Numerical Approximation_Experiment_Incomplete porting

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/computer-programming-responsive-iiith#68]
Defect Description:
In the experiment page of "Numerical Approximation" of this lab, total 4 sections are available in the page of **http://cse02-iiith.vlabs.ac.in/exp1/simulation/index.html**. Where as in the open edx page 3 sections are ported. Need to correct this.

Actual Result :
In the experiment page of "Numerical Approximation" of this lab, total 4 sections are available in the page of **http://cse02-iiith.vlabs.ac.in/exp1/simulation/index.html**. Where as in the open edx page 3 sections are ported.

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_cpl_i11](https://cloud.githubusercontent.com/assets/13479177/19962632/7093446c-a1da-11e6-8fe8-33b5c95c92df.png)

**Comment by sravanthimodepu** [comment]
The issue is not with the porting. As the graph in the simulation is overlapping, while trying to adjust the simulation's length and width to view it completely, the graph in the simulation is overlapping with the other components.
