### ISSUE TITLE
QA_Functions, Strings, Arrays, Structures_Quiz

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/computer-programming-responsive-iiith#71]
Defect Description:
The Quiz pages of "Functions, Strings, Arrays, Structures" experiments of this lab, are not ported. Need to be ported the section.

Actual Result :
The Quiz pages of "Functions, Strings, Arrays, Structures" experiments of this lab, are not ported. Need to be ported the section.

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_cpl14_i](https://cloud.githubusercontent.com/assets/13479177/19963474/65123ca2-a1de-11e6-9a92-2e00712c151b.png)

**Comment by sravanthimodepu** [comment]
Quiz section is ported  in "Functions, Strings, Arrays, Structures" experiments of this lab. Hence issue is fixed now.
