### ISSUE TITLE
QA_Strings_Theory_Broken link

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/computer-programming-responsive-iiith#72]
Defect Description:
In the Theory pages of "Strings" experiment of this lab, ASCII code link given in the content is broken. Need to assign the link with correct page. 

Actual Result :
In the Theory pages of "Strings" experiment of this lab, ASCII code link given in the content is broken. 

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_cpl_i15](https://cloud.githubusercontent.com/assets/13479177/19963555/b5cca574-a1de-11e6-9ecd-a149e702cd68.png)

**Comment by sravanthimodepu** [comment]
Link is updated and issue is fixed now.
