### ISSUE TITLE
QA_Functions_Quiz

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/computer-programming-responsive-iiith#73]
Defect Description:
The Quiz page of "Functions" experiment of this lab, unable to port all the questions as few questions contains boxes.

Actual Result :
The Quiz page of "Functions" experiment of this lab, unable to port all the questions as few questions contains boxes.

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_cpl_i16](https://cloud.githubusercontent.com/assets/13479177/19963699/5ddbf0c6-a1df-11e6-88d3-949828e84c49.png)

**Comment by sravanthimodepu** [comment]
While trying to port the 6th question in the quiz which is with the simple program,
![cp-functoins-quiz](https://cloud.githubusercontent.com/assets/11156924/26201627/90cfc2c6-3bf1-11e7-976f-8a6af022c483.png)
 displaying the below error.
