### ISSUE TITLE
QA_Computer_Programming_Simulations_Fullscreen

### ISSUE THREAD

**Issue by sravanthimodepu** [virtual-labs/computer-programming-responsive-iiith#76]
Defect Description:
In all the experiments, full screen button is missing while porting.

Actual Result :
In  all the experiments, full screen button is missing while porting. Full screen button should be there to view the full simulation.  

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Comment by sravanthimodepu** [comment]
Updated all the simulations with full screen button to view the complete simulation. Hence Issue is fixed.

**Comment by varshareddykumbham** [comment]
Commit id- 65b47a3
